(load "../common/math.scm")

;; Cube Root Guess Update Rule Using Average Damping
;;
;;   Guesses generated by the rule `y' <- x / y^2` may oscillate wildly and fail to approach the cube root, whereas
;;   guesses generated by the rule `y'' <- (x / y^2 + 2y) / 3` with average damping approach the cube root stably.
;;
;;   y = cbrt(x)
;;   y^3 = x
;;   y = x / y^2
;;   3y = x / y^2 + 2y
;;   y = (x / y^2 + 2y) / 3
;;
;; Cube Root by Iterating Until Reaching a Fixed Point
(define (cbrt x)
  ;; no error: y = y''
  (define (good-enough? guess next-guess)
    (= guess next-guess))
  ;; y'' <- (x / y^2 + 2y) / 3
  (define (improve guess)
    (/ (+ (/ x (square guess))
          (* 2 guess))
       3))
  (define (try guess)
    (let ((next-guess (improve guess)))
      (if (good-enough? guess next-guess)
          guess
          (try next-guess))))
  (try 1.0))
