(load "../common/testing.scm")
(load "prime.scm")

(test "prime0?"
      (lambda ()
        ;; Test for normal numbers.
        (assert-eq (prime0? 0) #f)
        (assert-eq (prime0? 1) #f)
        (assert-eq (prime0? 2) #t)
        (assert-eq (prime0? 3) #t)
        (assert-eq (prime0? 4) #f)
        (assert-eq (prime0? 5) #t)
        (assert-eq (prime0? 6) #f)
        (assert-eq (prime0? 7) #t)
        (assert-eq (prime0? 8) #f)
        (assert-eq (prime0? 9) #f)
        (assert-eq (prime0? 10) #f)
        (assert-eq (prime0? 11) #t)
        (assert-eq (prime0? 23) #t)
        (assert-eq (prime0? 149) #t)
        (assert-eq (prime0? 299) #f)
        (assert-eq (prime0? 529) #f)
        (assert-eq (prime0? 823) #t)
        (assert-eq (prime0? 1483) #t)
        ;; Test for Carmichael numbers.
        (assert-eq (prime0? 561) #f)
        (assert-eq (prime0? 1105) #f)
        (assert-eq (prime0? 1729) #f)
        (assert-eq (prime0? 2465) #f)
        (assert-eq (prime0? 2821) #f)
        (assert-eq (prime0? 6601) #f)))

(test "fast-prime1?"
      (lambda ()
        ;; Test for normal numbers.
        (assert-eq (fast-prime1? 0) #f)
        (assert-eq (fast-prime1? 1) #f)
        (assert-eq (fast-prime1? 2) #t)
        (assert-eq (fast-prime1? 3) #t)
        (assert-eq (fast-prime1? 4) #f)
        (assert-eq (fast-prime1? 5) #t)
        (assert-eq (fast-prime1? 6) #f)
        (assert-eq (fast-prime1? 7) #t)
        (assert-eq (fast-prime1? 8) #f)
        (assert-eq (fast-prime1? 9) #f)
        (assert-eq (fast-prime1? 10) #f)
        (assert-eq (fast-prime1? 11) #t)
        (assert-eq (fast-prime1? 23) #t)
        (assert-eq (fast-prime1? 149) #t)
        (assert-eq (fast-prime1? 299) #f)
        (assert-eq (fast-prime1? 529) #f)
        (assert-eq (fast-prime1? 823) #t)
        (assert-eq (fast-prime1? 1483) #t)
        ;; Test for Carmichael numbers (false positives).
        (assert-eq (fast-prime1? 561) #t)
        (assert-eq (fast-prime1? 1105) #t)
        (assert-eq (fast-prime1? 1729) #t)
        (assert-eq (fast-prime1? 2465) #t)
        (assert-eq (fast-prime1? 2821) #t)
        (assert-eq (fast-prime1? 6601) #t)))

(test "fast-prime2?"
      (lambda ()
        ;; Test for normal numbers.
        (assert-eq (fast-prime2? 0) #f)
        (assert-eq (fast-prime2? 1) #f)
        (assert-eq (fast-prime2? 2) #t)
        (assert-eq (fast-prime2? 3) #t)
        (assert-eq (fast-prime2? 4) #f)
        (assert-eq (fast-prime2? 5) #t)
        (assert-eq (fast-prime2? 6) #f)
        (assert-eq (fast-prime2? 7) #t)
        (assert-eq (fast-prime2? 8) #f)
        (assert-eq (fast-prime2? 9) #f)
        (assert-eq (fast-prime2? 10) #f)
        (assert-eq (fast-prime2? 11) #t)
        (assert-eq (fast-prime2? 23) #t)
        (assert-eq (fast-prime2? 149) #t)
        (assert-eq (fast-prime2? 299) #f)
        (assert-eq (fast-prime2? 529) #f)
        (assert-eq (fast-prime2? 823) #t)
        (assert-eq (fast-prime2? 1483) #t)
        ;; Test for Carmichael numbers.
        (assert-eq (fast-prime2? 561) #f)
        (assert-eq (fast-prime2? 1105) #f)
        (assert-eq (fast-prime2? 1729) #f)
        (assert-eq (fast-prime2? 2465) #f)
        (assert-eq (fast-prime2? 2821) #f)
        (assert-eq (fast-prime2? 6601) #f)))
