(load "../common/math.scm")

;; Square Root Guess Update Rule Using Average Damping
;;
;;   Guesses generated by the `y' <- x / y` rule may oscillate wildly and fail to approach the square root, whereas
;;   guesses generated by the `y'' <- (x / y + y) / 2` rule with average damping approach the square root stably.
;;
;;   y = sqrt(x)
;;   y^2 = x
;;   y = x / y
;;   2y = x / y + y
;;   y = (x / y + y) / 2
;;
;; Square Root by Iterating Until Reaching the Answer (BAD)
;;
;;   `good-enough1?` fails to terminate even for normal numbers.
;;   `good-enough2?` fails for very small and large numbers.
;;   `good-enough3?` addresses that issue, but still suffers from accuracy issues caused by the tolerance.
;;
(define (sqrt1 x)
  (define tolerance 0.001)
  ;; WORST: no error: y^2 = x
  (define (good-enough1? guess)
    (= (square guess) x))
  ;; WORSE: absolute error: |y^2 - x| < tolerance
  (define (good-enough2? guess)
    (< (abs_ (- (square guess) x)) tolerance))
  ;; BAD: relative error: |(y^2 - x) / x| < tolerance
  (define (good-enough3? guess)
    (< (abs_ (/ (- (square guess) x) x)) tolerance))
  ;; y'' <- (x / y + y) / 2
  (define (improve guess)
    (average (/ x guess) guess))
  (define (try guess)
    (if (good-enough3? guess)
        guess
        (try (improve guess))))
  (try 1.0))

;; Square Root by Iterating Until Reaching a Fixed Point (BEST)
;;
;;   `good-enough1?`, `good-enough2?`, and `good-enough3?` succeed for very small and large numbers.
;;   `good-enough1?` is the best for accuracy.
;;
(define (sqrt2 x)
  (define tolerance 0.00000000001)
  ;; BEST: no error: y = y''
  (define (good-enough1? guess next-guess)
    (= guess next-guess))
  ;; GOOD: absolute error: |y - y''| < tolerance
  (define (good-enough2? guess next-guess)
    (< (abs_ (- guess next-guess)) tolerance))
  ;; BETTER: relative error: |(y - y'') / y''| < tolerance
  (define (good-enough3? guess next-guess)
    (< (abs_ (/ (- guess next-guess) next-guess)) tolerance))
  ;; y'' <- (x / y + y) / 2
  (define (improve guess)
    (average (/ x guess) guess))
  (define (try guess)
    (let ((next-guess (improve guess)))
      (if (good-enough1? guess next-guess)
          guess
          (try next-guess))))
  (try 1.0))

(define sqrt_ sqrt2)
